In [1]:
from itertools import product
import numpy as np

In [2]:
def v (n, q):
    """construct a linear space of dimension n over a finite field of order q"""
    return [''.join(str(pos) for pos in comb) for comb in list(product(range(q), repeat=n))]

In [3]:
n = 2
q = 3
messages = np.array([list(i) for i in v(n, q)], dtype=int)
generator = np.array([['1', '0', '2', '2'], ['0', '1', '2', '1']], dtype=int)
code = np.mod(np.dot(messages, generator), q)

print('Messages')
print(messages)
print()
print('Standard-Form Generator')
print(generator)
print()
print('Code')
print(code)

Messages
[[0 0]
 [0 1]
 [0 2]
 [1 0]
 [1 1]
 [1 2]
 [2 0]
 [2 1]
 [2 2]]

Standard-Form Generator
[[1 0 2 2]
 [0 1 2 1]]

Code
[[0 0 0 0]
 [0 1 2 1]
 [0 2 1 2]
 [1 0 2 2]
 [1 1 1 0]
 [1 2 0 1]
 [2 0 1 1]
 [2 1 0 2]
 [2 2 2 0]]
